### PR TITLE
Fix bug of list scroll position losing

### PR DESCRIPTION
**Pull request by erfansn**
### Description
What you raised as a challenge on YouTube on the occasion of your channel reaching 1k.

### CODE REVIEW

**Comment by moallemi** [comment]
Thanks for the PR, @erfansn! 🙏

I'll review it by Monday and get back to you.

**Review by moallemi — APPROVED** [review]
Dear Erfan,

Thank you for your contribution! This partially addresses the issue and helps make the experience less frustrating for users. I'll be discussing it in more detail in an upcoming video.

**Comment by erfansn** [comment]
Although there are only 2 lines of code in appearance, if you want, we can explain it together in the form of a video.

**Comment by moallemi** [comment]
Good idea!

**Pull request merged**
